//
//  SearchMainWorker.swift
//  Bomapp
//
//  Created by Yong Seok Kim on 2020/07/04.
//  Copyright (c) 2020 Yong Seok Kim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SearchMainWorker {
    func getList(model: SearchMain.Repository.Request,
                 completion: @escaping (Bool, SearchMain.Repository.Response?) -> Void) {
        
        NetworkManager.shared.getSearchGitList(model: model) { model, error in
            if let _ = error {
                completion(false, nil)
            } else {
                if let m = model {
                    completion(true, model)
                }
            }
        }
    }
    
    func getUserList(model: SearchMain.User.Request,
                 completion: @escaping (Bool, SearchMain.User.Response?) -> Void) {
        
        NetworkManager.shared.getSearchGitUserList(model: model) { model, error in
            if let _ = error {
                completion(false, nil)
            } else {
                if let m = model {
                    completion(true, model)
                }
            }
        }
    }

}
