//
//  SearchMainModels.swift
//  Bomapp
//
//  Created by Yong Seok Kim on 2020/07/04.
//  Copyright (c) 2020 Yong Seok Kim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SearchMain {
    // MARK: Use cases
        enum Repository {
            struct Request{
                let q: String
                let sort: String
                let order: String
                let page: Int
            }
            struct Response: Codable {
                let total_count: Int
                let incomplete_results: Bool
                let items: [SearchResultModel]
            }
            struct ViewModel {
                var lastPage: Bool
                var page: Int
                var lists: [SearchResultModel]
            }
        }
    
    enum User {
        struct Request{
            let q: String
            let sort: String
            let order: String
            let page: Int
        }
        struct Response: Codable {
            let total_count: Int
            let incomplete_results: Bool
            let items: [OwnerModel]
        }
        struct ViewModel {
            var lastPage: Bool
            var page: Int
            var lists: [OwnerModel]
        }
    }

}


